import { EngineeringFeature, QfdRelation, QualityProblem, ReviewRecord, ScmRecommendation } from './types';

export const reviews: ReviewRecord[] = [
  {
    id: 'r1',
    model: '问界M9',
    platform: '懂车帝',
    date: '2026-01-15',
    aspect: '续航与能耗',
    subAspect: '冬季续航衰减',
    text: '冬天在东北开，续航直接缩水了快一半，零下十五度的时候纯电只能跑一百多公里，电池加热和BMS策略需要优化。',
    sentiment: 'negative',
    score: -0.86,
  },
  {
    id: 'r2',
    model: '问界M9',
    platform: '汽车之家',
    date: '2026-02-10',
    aspect: '智能座舱',
    subAspect: '车机多任务卡顿',
    text: '三联屏很震撼，但导航、音乐和副驾投屏一起跑的时候会有一两秒卡顿，像是SoC调度和内存管理没有跟上。',
    sentiment: 'negative',
    score: -0.68,
  },
  {
    id: 'r3',
    model: '特斯拉Model Y',
    platform: '微博',
    date: '2026-03-05',
    aspect: '舒适性与NVH',
    subAspect: '底盘悬架异响',
    text: '悬架调校偏硬，过减速带时震动直接传到座椅，左后轮偶尔还有明显挤压声。',
    sentiment: 'negative',
    score: -0.72,
  },
  {
    id: 'r4',
    model: '小米SU7',
    platform: '抖音',
    date: '2026-04-18',
    aspect: '智能驾驶',
    subAspect: '雨天雷达误报',
    text: '前天遇到大暴雨，高阶辅助驾驶被雨点干扰，频繁提示退出并自动紧急制动，需要优化雨雾识别。',
    sentiment: 'negative',
    score: -0.78,
  },
  {
    id: 'r5',
    model: '理想L9',
    platform: '懂车帝',
    date: '2026-02-22',
    aspect: '空间表现',
    subAspect: '高速风噪',
    text: '车里空间很大，但高速一百一以上A柱附近风噪明显，密封条和装配工艺还可以再优化。',
    sentiment: 'neutral',
    score: -0.35,
  },
  {
    id: 'r6',
    model: '问界M9',
    platform: '微博',
    date: '2026-02-01',
    aspect: '舒适性与NVH',
    subAspect: '空气悬架异响',
    text: '静止启动或者降车身的时候，空气悬架压缩机和分配阀声音很明显，听起来不像豪华车。',
    sentiment: 'negative',
    score: -0.82,
  },
  {
    id: 'r7',
    model: '比亚迪汉',
    platform: '汽车之家',
    date: '2026-01-20',
    aspect: '续航与能耗',
    subAspect: '空调升温慢',
    text: '北方冬天早上开空调，要等好几分钟才有热风，PTC加热和热泵控制策略还有提升空间。',
    sentiment: 'negative',
    score: -0.55,
  },
  {
    id: 'r8',
    model: '蔚来ES8',
    platform: '今日头条',
    date: '2026-03-12',
    aspect: '智能座舱',
    subAspect: '语音响应延迟',
    text: '智能语音有时候要等三秒才回应，尤其在地库网络差的时候，离线语音能力需要加强。',
    sentiment: 'neutral',
    score: -0.22,
  },
];

export const problems: QualityProblem[] = [
  {
    id: 'p1',
    name: '冬季续航里程严重衰减',
    aspect: '续航与能耗',
    attention: 92.5,
    dissatisfaction: 85,
    intensity: 8.8,
    pi: 69.2,
    kano: 'Must-be',
    attribution: '低温环境下电池热损耗偏大，热泵制热效率与BMS低温管理策略协同不足。',
    typicalComments: ['冬天标称四百多公里，实际高速加空调只能跑二百多公里。', '零下十度时电池预热耗电明显，续航掉得快。'],
  },
  {
    id: 'p2',
    name: '空气悬架阀体及压缩机异常震响',
    aspect: '舒适性与NVH',
    attention: 78,
    dissatisfaction: 80,
    intensity: 8.2,
    pi: 51.2,
    kano: 'Must-be',
    attribution: '空气悬架分配阀加工精度、压缩机声学包设计与悬浮支架紧固力矩存在协同优化空间。',
    typicalComments: ['降车身的时候车底会传来明显金属声。', '空气悬架动作时压缩机噪声在车库里特别明显。'],
  },
  {
    id: 'p3',
    name: '激光雷达极端雨天干扰误报',
    aspect: '智能驾驶',
    attention: 88,
    dissatisfaction: 64,
    intensity: 8.5,
    pi: 47.9,
    kano: 'Must-be',
    attribution: '雨点噪声识别、点云滤波阈值与传感器清洁策略需要联合调校。',
    typicalComments: ['大雨天高阶辅助驾驶频繁退出。', '雨水反射导致系统误判，制动介入比较突兀。'],
  },
  {
    id: 'p4',
    name: '多任务状态下车机系统顿挫卡顿',
    aspect: '智能座舱',
    attention: 86,
    dissatisfaction: 72,
    intensity: 7.5,
    pi: 46.4,
    kano: 'One-dimensional',
    attribution: '内存占用、SoC高温调频、多媒体线程优先级与多屏流转策略存在耦合问题。',
    typicalComments: ['导航和投屏一起开时会卡一两秒。', '多屏流转偶尔黑屏，体验不够稳定。'],
  },
];

export const engineeringFeatures: EngineeringFeature[] = [
  { id: 'e1', name: '电池低温热管理传热效率', unit: 'W/K', current: '145', target: '180' },
  { id: 'e2', name: '低温BMS加热响应时间', unit: 's', current: '320', target: '180' },
  { id: 'e3', name: '电池预热总输出功率', unit: 'kW', current: '4.5', target: '7.5' },
  { id: 'e4', name: '座舱系统内存空余占比', unit: '%', current: '8.2', target: '25.0' },
  { id: 'e5', name: '主CPU大核高热调频上限', unit: '℃', current: '92', target: '105' },
  { id: 'e6', name: '空气悬架分配阀加工精度', unit: 'μm', current: '8.5', target: '3.0' },
  { id: 'e7', name: '雨天点云噪声滤波F-score', unit: 'F-score', current: '0.78', target: '0.94' },
];

export const qfdRelations: QfdRelation[] = [
  { problemId: 'p1', featureId: 'e1', weight: 9 },
  { problemId: 'p1', featureId: 'e2', weight: 9 },
  { problemId: 'p1', featureId: 'e3', weight: 3 },
  { problemId: 'p2', featureId: 'e6', weight: 9 },
  { problemId: 'p3', featureId: 'e7', weight: 9 },
  { problemId: 'p3', featureId: 'e5', weight: 3 },
  { problemId: 'p4', featureId: 'e4', weight: 9 },
  { problemId: 'p4', featureId: 'e5', weight: 9 },
];

export const scmRecommendations: ScmRecommendation[] = [
  {
    featureId: 'e1',
    module: '动力电池包及热流总成',
    collaborators: ['电池供应商', '热管理供应商'],
    internalTeams: ['三电系统部门', '整车热工实验室'],
    method: '联合开展低温热管理台架试验，优化液冷流道和导热材料参数。',
    suggestion: '建立热管理仿真共享机制，推动电池包结构与热泵控制策略协同优化。',
    urgency: '高',
    cost: '高',
  },
  {
    featureId: 'e2',
    module: '电池管理系统BMS',
    collaborators: ['BMS软件供应商', '整车控制供应商'],
    internalTeams: ['整车软件控制部', 'BMS标定团队'],
    method: '联合标定低温场景加热响应曲线，缩短预热触发与控制闭环时间。',
    suggestion: '通过OTA优化低温预热策略，并建立极寒道路验证样本库。',
    urgency: '高',
    cost: '中',
  },
  {
    featureId: 'e4',
    module: '智能座舱域控模块',
    collaborators: ['芯片供应商', '车机软件供应商'],
    internalTeams: ['智能座舱部门', 'HMI体验团队'],
    method: '联合定位多屏并发、导航渲染、音视频解码场景下的资源竞争问题。',
    suggestion: '优化内存回收、线程优先级和高温调频策略，减少高负载卡顿。',
    urgency: '中',
    cost: '中',
  },
  {
    featureId: 'e6',
    module: '电子控制空气悬架系统',
    collaborators: ['悬架阀体供应商', '空气弹簧供应商'],
    internalTeams: ['底盘开发部', 'NVH实验室'],
    method: '开展阀体加工公差、橡胶衬套硬度和压缩机声学包联合验证。',
    suggestion: '对高频异响样件进行批次追踪，形成供应链模块化整改清单。',
    urgency: '高',
    cost: '高',
  },
  {
    featureId: 'e7',
    module: '高阶智能驾驶感知模块',
    collaborators: ['激光雷达供应商', '感知算法合作方'],
    internalTeams: ['智能驾驶部门', '感知融合团队'],
    method: '联合复现暴雨、强反光、低能见度场景，调整点云滤波和降噪阈值。',
    suggestion: '建立极端天气感知数据集，推进传感器固件与算法参数同步迭代。',
    urgency: '高',
    cost: '中',
  },
];

export const warnings = [
  { date: '2026-01-18', title: '冬季热管理投诉热度上升', level: '红色高危', model: '问界M9 / 智界S7' },
  { date: '2026-02-08', title: '底盘空气悬架异响讨论升温', level: '橙色预警', model: '极氪001 / 问界M9' },
  { date: '2026-04-20', title: '雨天智能驾驶误报增加', level: '黄色警戒', model: '小米SU7' },
];

export const reports = [
  { title: 'PQ-SCM 2026一季度感知质量三维诊断报告.pdf', type: 'PDF', size: '12.4 MB', date: '2026-04-01' },
  { title: '问界M9空气悬架协同改进建议书.docx', type: 'Word', size: '4.8 MB', date: '2026-03-10' },
  { title: '新能源汽车QFD特征转换矩阵明细表.xlsx', type: 'Excel', size: '1.2 MB', date: '2026-04-25' },
];
